@baseUrl = http://localhost:5000/

# создание пользователя
POST {{baseUrl}}/user
Content-Type: application/json

{
  "email": "user_1@mail.ru",
  "password": "vERy_l00ngPassword"
}

###

# получение информации о пользователе
GET {{baseUrl}}user/1
Content-Type: application/json

###

# обновление пользователя
PATCH {{baseUrl}}/user/2
Content-Type: application/json
Authorization: Basic user_1@mail.ru:vERy_l00ngPassword

{
  "email": "user_2@mail.ru",
  "password": "vERy_l00ngPassword"
}

###

# удаление пользователя
DELETE {{baseUrl}}/user/2
Authorization: Basic user_1@mail.ru:vERy_l00ngPassword
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advert
Content-Type: application/json
Authorization: Basic user_1@mail.ru:vERy_l00ngPassword

{
  "title": "Selling phone",
  "description": "iPhone X, brand-new"
}

###

# получение информации по объявлению
GET {{baseUrl}}advert/1
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/advert/1
Content-Type: application/json
Authorization: Basic user_1@mail.ru:vERy_l00ngPassword

{
  "description": "iPhone X, brand-new, some scratches"
}

###

# удаление объявления
DELETE {{baseUrl}}/advert/1
Content-Type: application/json
Authorization: Basic user_1@mail.ru:vERy_l00ngPassword

###